name: todo_asla
description: todo

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter

  # подключаем локализации из SDK
  flutter_localizations:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0


dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true